### ISSUE TITLE
Participantsのkick機能

### ISSUE THREAD

**Issue by kyuuuuuji** [teinen/planning-poker-app#30]
いつもajapoにはお世話になってます！
「あると嬉しい」程度の要望ですのでお暇なときに……という感じです（し、自分で作れよという話でもある）が、Participantsをkickできると助かるな〜と思い起票しました。

シナリオ的には下記のような流れです。
1. Participantsのうち一人が誤ってタブを閉じてしまう
2. roomは継続して使いたいため、タブを閉じた人がURLから再参加
3. 別のParticipantsとして認識されるため、古いParticipantsの存在がノイズとなる
4. ownerが古いParticipantsをkickして整理

スクショは参考ですが、最近このようなことがチラホラと……

![スクリーンショット 2022-11-16 19 00 11](https://user-images.githubusercontent.com/8536086/202149905-d138db81-84a7-4344-96ba-1f48e11b933b.png)

**Comment by teinen** [comment]
そもそも `sessionStorage` じゃなくて `localStorage` で永続化して、新しく参加したら上書き、でもいいかもしれないな

**Comment by teinen** [comment]
Room 周りの改善

- 新規 room 作成時
  - [x] 必ず roomId と participantId を storage に保存する
  - [x] すでに存在するかどうかに関わらず保存
- 既存の room 参加時
  - [x] storage の id を取得し、参加済みのユーザーであればそのまま参加する
  - [x] 未参加ユーザーであれば join modal を表示する
  - [x] room が存在しなければ、アラートを表示し top へ遷移する
